import {
  BRAND,
  colors,
  spacing,
  spacingLegacy,
  radius,
  elevation,
  motion,
  iconSize,
  typography,
  layout,
  componentSize,
} from './src/constants/designTokens.js';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        app: {
          bg: colors.surface.bg,
          surface: colors.surface.surface,
          card: colors.surface.card,
          elevated: colors.surface.elevated,
          text: colors.text.primary,
          muted: colors.text.secondary,
          subtle: colors.text.subtle,
          border: colors.surface.border,
          divider: colors.surface.divider,
          overlay: colors.surface.overlay,
          disabled: colors.surface.disabled,
          'primary-soft': colors.surface.primarySoft,
          'text-disabled': colors.text.disabled,
          'text-inverse': colors.text.inverse,
        },
        primary: {
          DEFAULT: colors.primary[600],
          50: colors.primary[50],
          100: colors.primary[100],
          200: colors.primary[200],
          300: colors.primary[300],
          400: colors.primary[400],
          500: colors.primary[500],
          600: colors.primary[600],
          700: colors.primary[700],
          800: colors.primary[800],
          900: colors.primary[900],
        },
        success: {
          DEFAULT: colors.success[600],
          50: colors.success[50],
          100: colors.success[100],
          200: colors.success[200],
          300: colors.success[300],
          400: colors.success[400],
          500: colors.success[500],
          600: colors.success[600],
          700: colors.success[700],
          800: colors.success[800],
          900: colors.success[900],
        },
        warning: {
          DEFAULT: colors.warning[600],
          50: colors.warning[50],
          100: colors.warning[100],
          200: colors.warning[200],
          300: colors.warning[300],
          400: colors.warning[400],
          500: colors.warning[500],
          600: colors.warning[600],
          700: colors.warning[700],
          800: colors.warning[800],
          900: colors.warning[900],
        },
        error: {
          DEFAULT: colors.error[600],
          50: colors.error[50],
          100: colors.error[100],
          200: colors.error[200],
          300: colors.error[300],
          400: colors.error[400],
          500: colors.error[500],
          600: colors.error[600],
          700: colors.error[700],
          800: colors.error[800],
          900: colors.error[900],
        },
      },
      fontFamily: {
        sans: BRAND.fontFamily.split(',').map((f) => f.trim().replace(/^["']|["']$/g, '')),
      },
      spacing: {
        // Canonical design-system scale
        'space-xs': `${spacing.xs}px`,
        'space-sm': `${spacing.sm}px`,
        'space-md': `${spacing.md}px`,
        'space-base': `${spacing.base}px`,
        'space-lg': `${spacing.lg}px`,
        'space-xl': `${spacing.xl}px`,
        'space-2xl': `${spacing['2xl']}px`,
        'space-3xl': `${spacing['3xl']}px`,
        'space-4xl': `${spacing['4xl']}px`,
        'space-5xl': `${spacing['5xl']}px`,
        // Legacy aliases (auth/onboarding — keep values stable)
        xs: `${spacingLegacy.xs}px`,
        sm: `${spacingLegacy.sm}px`,
        md: `${spacingLegacy.md}px`,
        lg: `${spacingLegacy.lg}px`,
        xl: `${spacingLegacy.xl}px`,
        safe: 'env(safe-area-inset-bottom)',
        'page-x': `${layout.pagePaddingX}px`,
        'page-y': `${layout.pagePaddingY}px`,
        'section': `${layout.sectionGap}px`,
      },
      fontSize: {
        display: [
          `${typography.display.size}px`,
          {
            lineHeight: String(typography.display.lineHeight),
            fontWeight: String(typography.display.weight),
            letterSpacing: typography.display.letterSpacing,
          },
        ],
        'heading-xl': [
          `${typography.headingXl.size}px`,
          {
            lineHeight: String(typography.headingXl.lineHeight),
            fontWeight: String(typography.headingXl.weight),
            letterSpacing: typography.headingXl.letterSpacing,
          },
        ],
        'heading-l': [
          `${typography.headingL.size}px`,
          {
            lineHeight: String(typography.headingL.lineHeight),
            fontWeight: String(typography.headingL.weight),
            letterSpacing: typography.headingL.letterSpacing,
          },
        ],
        'heading-m': [
          `${typography.headingM.size}px`,
          {
            lineHeight: String(typography.headingM.lineHeight),
            fontWeight: String(typography.headingM.weight),
            letterSpacing: typography.headingM.letterSpacing,
          },
        ],
        title: [
          `${typography.title.size}px`,
          {
            lineHeight: String(typography.title.lineHeight),
            fontWeight: String(typography.title.weight),
            letterSpacing: typography.title.letterSpacing,
          },
        ],
        subtitle: [
          `${typography.subtitle.size}px`,
          {
            lineHeight: String(typography.subtitle.lineHeight),
            fontWeight: String(typography.subtitle.weight),
          },
        ],
        body: [
          `${typography.body.size}px`,
          { lineHeight: String(typography.body.lineHeight) },
        ],
        'body-small': [
          `${typography.bodySmall.size}px`,
          { lineHeight: String(typography.bodySmall.lineHeight) },
        ],
        small: [
          `${typography.bodySmall.size}px`,
          { lineHeight: String(typography.bodySmall.lineHeight) },
        ],
        caption: [
          `${typography.caption.size}px`,
          { lineHeight: String(typography.caption.lineHeight) },
        ],
        button: [
          `${typography.button.size}px`,
          {
            lineHeight: String(typography.button.lineHeight),
            fontWeight: String(typography.button.weight),
          },
        ],
        label: [
          `${typography.label.size}px`,
          {
            lineHeight: String(typography.label.lineHeight),
            fontWeight: String(typography.label.weight),
          },
        ],
      },
      borderRadius: {
        'radius-sm': `${radius.sm}px`,
        'radius-md': `${radius.md}px`,
        'radius-lg': `${radius.lg}px`,
        'radius-xl': `${radius.xl}px`,
        'radius-circular': `${radius.circular}px`,
        'btn-primary': `${radius.btnPrimary}px`,
        'btn-secondary': `${radius.btnSecondary}px`,
      },
      boxShadow: {
        'elevation-1': elevation[1],
        'elevation-2': elevation[2],
        'elevation-3': elevation[3],
        'elevation-4': elevation[4],
      },
      transitionDuration: {
        fast: motion.duration.fast,
        normal: motion.duration.normal,
        slow: motion.duration.slow,
      },
      transitionTimingFunction: {
        out: motion.easing.out,
        standard: motion.easing.standard,
      },
      height: {
        'btn-primary': `${componentSize.button.primaryMobile.height}px`,
        'btn-sm': `${componentSize.button.sm.height}px`,
        'btn-md': `${componentSize.button.md.height}px`,
        'btn-lg': `${componentSize.button.lg.height}px`,
        'btn-secondary': `${componentSize.button.secondaryMobile.height}px`,
        'input-md': `${componentSize.input.height}px`,
        logo: `${layout.logoMaxHeight}px`,
        'onboarding-ill': `${layout.onboardingIllustrationMax}px`,
        'icon-sm': `${iconSize.sm}px`,
        'icon-md': `${iconSize.md}px`,
        'icon-lg': `${iconSize.lg}px`,
        'icon-xl': `${iconSize.xl}px`,
        'topbar': '48px',
      },
      width: {
        'icon-sm': `${iconSize.sm}px`,
        'icon-md': `${iconSize.md}px`,
        'icon-lg': `${iconSize.lg}px`,
        'icon-xl': `${iconSize.xl}px`,
      },
      maxWidth: {
        screen: layout.maxWidth.screen,
        content: layout.maxWidth.content,
        wide: layout.maxWidth.wide,
      },
      maxHeight: {
        logo: `${layout.logoMaxHeight}px`,
        'onboarding-ill': `${layout.onboardingIllustrationMax}px`,
        'hero-mobile': '35dvh',
      },
      minHeight: {
        'onboarding-ill': `${layout.onboardingIllustrationMin}px`,
        touch: `${componentSize.touch}px`,
      },
      zIndex: {
        overlay: '40',
        modal: '50',
        toast: '60',
        nav: '50',
      },
    },
  },
  plugins: [],
};
