import {
  Award,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  AtSign,
  BadgeCheck,
  Bell,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Landmark,
  Clock,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  FolderKanban,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Image,
  Info,
  Languages,
  LayoutDashboard,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Menu,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Moon,
  Lock,
  Newspaper,
  Pencil,
  Phone,
  Plus,
  PlusSquare,
  Save,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tags,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  WifiOff,
  Wrench,
  X,
  Reply,
} from 'lucide-react';

/** Re-export all Lucide icons from a single place */
export {
  Award,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  AtSign,
  BadgeCheck,
  Bell,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Landmark,
  Clock,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  FolderKanban,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Image,
  Info,
  Languages,
  LayoutDashboard,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Menu,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Moon,
  Lock,
  Newspaper,
  Pencil,
  Phone,
  Plus,
  PlusSquare,
  Save,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tags,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  WifiOff,
  Wrench,
  X,
  Reply,
};

/**
 * Icon size tokens (Lucide) — sm 16 · md/default 18 · lg 20 · nav 20 · xl 24
 * Prefer these over arbitrary sizes. Stroke: 2 (default).
 */
export const ICON_SIZES = {
  sm: 16,
  md: 18,
  default: 18,
  lg: 20,
  nav: 20,
  xl: 24,
};

export const ICON_STROKE = {
  default: 2,
  thin: 1.5,
  bold: 2.25,
};

/** Active: brand blue · inactive: slate gray */
export const ICON_COLORS = {
  default: 'text-app-text',
  primary: 'text-primary-600 dark:text-primary-400',
  inactive: 'text-app-subtle',
  muted: 'text-app-subtle',
  positive: 'text-success-600',
};

/** Quiet icon surface for section headers — no loud brand wash */
export const ICON_SURFACE_CLASS =
  'bg-app-surface text-app-muted ring-1 ring-app-border';

/** Bottom navigation */
export const NAV_ICONS = {
  home: Home,
  briefcase: Briefcase,
  bell: Bell,
  user: User,
  dashboard: LayoutDashboard,
  publish: PlusSquare,
  building: Building2,
};

/** Profile section headers */
export const PROFILE_SECTION_ICONS = {
  about: User,
  experience: Briefcase,
  education: GraduationCap,
  certification: Award,
  skills: Sparkles,
  service: Wrench,
  document: FileText,
  contact: Mail,
  social: Share2,
  language: Languages,
  preferences: Target,
  projects: FolderKanban,
};

/** Semantic aliases for common actions */
export const ACTION_ICONS = {
  search: Search,
  filter: Filter,
  view: Eye,
  apply: FileText,
  edit: Pencil,
  save: Save,
  close: X,
  upload: Upload,
  download: Download,
  settings: Settings,
  share: Share2,
  email: Mail,
  phone: Phone,
  copy: Copy,
  contact: Phone,
  verify: ShieldCheck,
  verified: BadgeCheck,
};
