import {
  Award,
  AlertTriangle,
  BadgeCheck,
  Bell,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChevronDown,
  ChevronRight,
  Clock,
  Copy,
  Download,
  Eye,
  FileText,
  Filter,
  Flag,
  Globe,
  GraduationCap,
  Headphones,
  Home,
  Languages,
  LayoutDashboard,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreVertical,
  Moon,
  Newspaper,
  Pencil,
  Phone,
  Plus,
  PlusSquare,
  Save,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  Trash2,
  Upload,
  User,
  Users,
  Wrench,
  X,
} from 'lucide-react';

/** Re-export all Lucide icons from a single place */
export {
  Award,
  AlertTriangle,
  BadgeCheck,
  Bell,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChevronDown,
  ChevronRight,
  Clock,
  Copy,
  Download,
  Eye,
  FileText,
  Filter,
  Flag,
  Globe,
  GraduationCap,
  Headphones,
  Home,
  Languages,
  LayoutDashboard,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreVertical,
  Moon,
  Newspaper,
  Pencil,
  Phone,
  Plus,
  PlusSquare,
  Save,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  Trash2,
  Upload,
  User,
  Users,
  Wrench,
  X,
};

/** Compact scale — Default: 18px · Navigation: 22px */
export const ICON_SIZES = {
  default: 18,
  nav: 22,
  sm: 16,
  lg: 20,
};

/** Primary #2563EB · Inactive #64748B — icons inherit via text-* */
export const ICON_COLORS = {
  primary: 'text-primary-600',
  inactive: 'text-slate-500',
  muted: 'text-gray-400',
};

/** Bottom navigation */
export const NAV_ICONS = {
  home: Home,
  briefcase: Briefcase,
  bell: Bell,
  user: User,
  dashboard: LayoutDashboard,
  publish: PlusSquare,
  building: Building2,
};

/** Profile section headers */
export const PROFILE_SECTION_ICONS = {
  about: User,
  experience: Briefcase,
  education: GraduationCap,
  certification: Award,
  skills: Sparkles,
  service: Wrench,
  document: FileText,
  contact: Mail,
  language: Languages,
  preferences: Target,
};

/** Semantic aliases for common actions */
export const ACTION_ICONS = {
  search: Search,
  filter: Filter,
  view: Eye,
  apply: FileText,
  edit: Pencil,
  save: Save,
  close: X,
  upload: Upload,
  download: Download,
  settings: Settings,
  share: Share2,
  email: Mail,
  phone: Phone,
  copy: Copy,
  contact: Phone,
  verify: ShieldCheck,
  verified: BadgeCheck,
};
